package view;

import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;

/**
 *
 * @author ZAFL
 */
public class FramePokedex extends javax.swing.JFrame {

  /**
   * Creates new form FramePokedex
   */
  public FramePokedex() {
    initComponents();
    setLocationRelativeTo(null);
    FramePokemon frPokemon = new FramePokemon();
    addFrame(frPokemon);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    menuLogin = new javax.swing.JMenuItem();
    menuLogout = new javax.swing.JMenuItem();
    menuExit = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    menuPokemon = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(960, 540));
    setPreferredSize(new java.awt.Dimension(960, 540));

    javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
    desktopPane.setLayout(desktopPaneLayout);
    desktopPaneLayout.setHorizontalGroup(
      desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 960, Short.MAX_VALUE)
    );
    desktopPaneLayout.setVerticalGroup(
      desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 517, Short.MAX_VALUE)
    );

    jMenu1.setText("Menu");

    menuLogin.setText("Login");
    jMenu1.add(menuLogin);

    menuLogout.setText("Logout");
    jMenu1.add(menuLogout);

    menuExit.setText("Exit");
    jMenu1.add(menuExit);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Pokedex");

    menuPokemon.setText("Pokemon");
    menuPokemon.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuPokemonActionPerformed(evt);
      }
    });
    jMenu2.add(menuPokemon);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPokemonActionPerformed
    FramePokemon frPokemon = new FramePokemon();
    addFrame(frPokemon);
  }//GEN-LAST:event_menuPokemonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FramePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FramePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FramePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FramePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FramePokedex().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem menuExit;
  private javax.swing.JMenuItem menuLogin;
  private javax.swing.JMenuItem menuLogout;
  private javax.swing.JMenuItem menuPokemon;
  // End of variables declaration//GEN-END:variables

  private void addFrame(JInternalFrame internalFrame) {
    if (desktopPane.getAllFrames().length > 0) {
      desktopPane.remove(0);
    }
    desktopPane.add(internalFrame);
    try {
      internalFrame.setMaximum(true);
    } catch (PropertyVetoException pve) {
      System.err.println(pve.getMessage());
    }
    internalFrame.setVisible(true);
    internalFrame.toFront();
  }
}
