package view;

import controller.QueryExecutor;
import controller.CRUDPokemon;
import java.awt.event.ItemEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Pokemon;
import utilities.ComboBoxItem;

/**
 *
 * @author ZAFL
 */
public class FramePokemon extends javax.swing.JInternalFrame {

  QueryExecutor queryExe = new QueryExecutor();
  CRUDPokemon crudPokemon = new CRUDPokemon();

  /**
   * Creates new form Pokemon
   */
  public FramePokemon() {
    initComponents();
    ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    ((BasicInternalFrameUI) this.getUI()).setEastPane(null);
    ((BasicInternalFrameUI) this.getUI()).setSouthPane(null);
    ((BasicInternalFrameUI) this.getUI()).setWestPane(null);
    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

    // tampilan utama
    addItem2ComboBox(cbTipePokemon, "tipe", true);
    loadTable("");

    jLabel9.setVisible(false);
    tfID.setVisible(false);

    // tampilan dialog
    getID();
    addItem2ComboBox(cbTipePokemon1Dlg, "tipe", false);
    addItem2ComboBox(cbTipePokemon2Dlg, "tipe", false);
    addItem2ComboBox(cbKemampuanPokemon1Dlg, "kemampuan", false);
    addItem2ComboBox(cbKemampuanPokemon2Dlg, "kemampuan", false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    dlTambahPokemon = new javax.swing.JDialog();
    dialogTitle = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    tfPokedexIDDlg = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    tfNamaPokemonDlg = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    cbTipePokemon1Dlg = new javax.swing.JComboBox<>();
    cbTipePokemon2Dlg = new javax.swing.JComboBox<>();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    cbKemampuanPokemon1Dlg = new javax.swing.JComboBox<>();
    cbKemampuanPokemon2Dlg = new javax.swing.JComboBox<>();
    btnTambahDlg = new javax.swing.JButton();
    btnClearDlg = new javax.swing.JButton();
    jLabel9 = new javax.swing.JLabel();
    tfID = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    tfTinggiDlg = new javax.swing.JTextField();
    tfBeratDlg = new javax.swing.JTextField();
    popUpTabel = new javax.swing.JPopupMenu();
    menuEdit = new javax.swing.JMenuItem();
    menuHapus = new javax.swing.JMenuItem();
    jScrollPane1 = new javax.swing.JScrollPane();
    tbPokemon = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    tfCariNama = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    cbTipePokemon = new javax.swing.JComboBox<>();
    btnTambah = new javax.swing.JButton();

    dlTambahPokemon.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    dlTambahPokemon.setMinimumSize(new java.awt.Dimension(400, 640));

    dialogTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    dialogTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    dialogTitle.setText("Tambah  Pokémon");

    jLabel5.setText("Pokedex ID");

    jLabel6.setText("Nama");

    jLabel7.setText("Tipe ke 1");

    jLabel8.setText("Tipe ke 2");

    jLabel10.setText("Kemampuan ke 1");

    jLabel11.setText("Kemampuan ke 2");

    btnTambahDlg.setText("Tambah");
    btnTambahDlg.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTambahDlgActionPerformed(evt);
      }
    });

    btnClearDlg.setText("Clear");
    btnClearDlg.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnClearDlgActionPerformed(evt);
      }
    });

    jLabel9.setText("ID Pokemon");
    jLabel9.setMinimumSize(new java.awt.Dimension(0, 0));

    tfID.setMinimumSize(new java.awt.Dimension(0, 0));

    jLabel12.setText("Tinggi");

    jLabel13.setText("Berat");

    javax.swing.GroupLayout dlTambahPokemonLayout = new javax.swing.GroupLayout(dlTambahPokemon.getContentPane());
    dlTambahPokemon.getContentPane().setLayout(dlTambahPokemonLayout);
    dlTambahPokemonLayout.setHorizontalGroup(
      dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dlTambahPokemonLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(dialogTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(dlTambahPokemonLayout.createSequentialGroup()
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel8)
                .addComponent(jLabel7)
                .addComponent(jLabel6)
                .addComponent(jLabel5)
                .addComponent(jLabel10)
                .addComponent(jLabel11)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(dlTambahPokemonLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel13)
                  .addComponent(jLabel12))))
            .addGap(18, 18, 18)
            .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(tfNamaPokemonDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(tfID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfPokedexIDDlg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
              .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(tfBeratDlg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addComponent(tfTinggiDlg, javax.swing.GroupLayout.Alignment.LEADING))
              .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(cbKemampuanPokemon2Dlg, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)
                .addComponent(cbKemampuanPokemon1Dlg, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(cbTipePokemon2Dlg, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)
                  .addComponent(cbTipePokemon1Dlg, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGap(0, 38, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlTambahPokemonLayout.createSequentialGroup()
            .addComponent(btnTambahDlg)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClearDlg)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    dlTambahPokemonLayout.setVerticalGroup(
      dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(dlTambahPokemonLayout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(dialogTitle)
        .addGap(40, 40, 40)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(tfPokedexIDDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(tfNamaPokemonDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel12)
          .addComponent(tfTinggiDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel13)
          .addComponent(tfBeratDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel7)
          .addComponent(cbTipePokemon1Dlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8)
          .addComponent(cbTipePokemon2Dlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel10)
          .addComponent(cbKemampuanPokemon1Dlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel11)
          .addComponent(cbKemampuanPokemon2Dlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(57, 57, 57)
        .addGroup(dlTambahPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnTambahDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnClearDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(66, Short.MAX_VALUE))
    );

    popUpTabel.setInvoker(tbPokemon);

    menuEdit.setText("Edit");
    menuEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuEditActionPerformed(evt);
      }
    });
    popUpTabel.add(menuEdit);

    menuHapus.setText("Hapus");
    menuHapus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuHapusActionPerformed(evt);
      }
    });
    popUpTabel.add(menuHapus);

    setBackground(new java.awt.Color(255, 255, 255));

    tbPokemon.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {},
        {},
        {},
        {}
      },
      new String [] {

      }
    ));
    tbPokemon.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        tbPokemonMouseReleased(evt);
      }
    });
    jScrollPane1.setViewportView(tbPokemon);

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Daftar Pokémon");

    jLabel2.setText("Nama");

    jLabel3.setText("Tipe");

    cbTipePokemon.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cbTipePokemonItemStateChanged(evt);
      }
    });

    btnTambah.setText("Tambah");
    btnTambah.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTambahActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addComponent(btnTambah)
        .addGap(152, 152, 152)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(tfCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(50, 50, 50)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(cbTipePokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(232, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap(20, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(tfCariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3)
          .addComponent(cbTipePokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(20, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    showDialog("Tambah Pokémon", true);
    System.out.println("ID: " + tfID.getText());
  }//GEN-LAST:event_btnTambahActionPerformed

  private void btnTambahDlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDlgActionPerformed
    ArrayList<Integer> tipe = new ArrayList<>();
    ArrayList<Integer> kemampuan = new ArrayList<>();

    String ID = tfID.getText();
    String pokedexID = tfPokedexIDDlg.getText();
    String namaPokemon = tfNamaPokemonDlg.getText();
    String tinggiPokemon = tfTinggiDlg.getText();
    String beratPokemon = tfBeratDlg.getText();
    String tipe1 = (String) cbTipePokemon1Dlg.getSelectedItem();
    String tipe2 = (String) cbTipePokemon2Dlg.getSelectedItem();
    String kemampuan1 = (String) cbKemampuanPokemon1Dlg.getSelectedItem();
    String kemampuan2 = (String) cbKemampuanPokemon2Dlg.getSelectedItem();

    if (pokedexID.isEmpty()) {
      JOptionPane.showMessageDialog(null, "Isikan field Pokedex ID");
    } else if (namaPokemon.isEmpty()) {
      JOptionPane.showMessageDialog(null, "Isikan field Nama Pokemon");
    } else if (cbTipePokemon1Dlg.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(null, "Pilih tipe ke 1 Pokemon");
    } else if (cbTipePokemon2Dlg.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(null, "Pilih tipe ke 2 Pokemon");
    } else if (cbKemampuanPokemon1Dlg.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(null, "Pilih kemampuan ke 1 Pokemon");
    } else if (cbKemampuanPokemon2Dlg.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(null, "Pilih kemampuan ke21 Pokemon");
    } else {
      tipe.add(Integer.valueOf(tipe1.replaceAll("[^0-9]", "")));
      tipe.add(Integer.valueOf(tipe2.replaceAll("[^0-9]", "")));
      kemampuan.add(Integer.valueOf(kemampuan1.replaceAll("[^0-9]", "")));
      kemampuan.add(Integer.valueOf(kemampuan2.replaceAll("[^0-9]", "")));
      Pokemon pokemon = new Pokemon(
              Integer.parseInt(ID),
              Integer.parseInt(pokedexID),
              namaPokemon,
              Float.parseFloat(tinggiPokemon),
              Float.parseFloat(beratPokemon),
              tipe,
              kemampuan
      );

      if (crudPokemon.tambah(pokemon) == 1) {
        crudPokemon.tambahTableMany2Many(pokemon, "tipe");
        crudPokemon.tambahTableMany2Many(pokemon, "kemampuan");
      } else {
        JOptionPane.showMessageDialog(null, "Error saat insert ke tabel");
      }
    }
  }//GEN-LAST:event_btnTambahDlgActionPerformed

  private void btnClearDlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDlgActionPerformed
    clearFieldDialog();
  }//GEN-LAST:event_btnClearDlgActionPerformed

  private void cbTipePokemonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipePokemonItemStateChanged
    if (cbTipePokemon.getItemAt(cbTipePokemon.getSelectedIndex()).getId() != 0 && evt.getStateChange() == ItemEvent.SELECTED) {
      String tipe = cbTipePokemon.getItemAt(cbTipePokemon.getSelectedIndex()).getNama();
      loadTable(tipe);
    }
  }//GEN-LAST:event_cbTipePokemonItemStateChanged

  private void tbPokemonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPokemonMouseReleased
    if (evt.isPopupTrigger()) {
      JTable source = (JTable) evt.getSource();
      int row = source.rowAtPoint(evt.getPoint());
      int column = source.columnAtPoint(evt.getPoint());

      if (!source.isRowSelected(row)) {
        source.changeSelection(row, column, false, false);
      }
      popUpTabel.show(evt.getComponent(), evt.getX(), evt.getY());
    }
  }//GEN-LAST:event_tbPokemonMouseReleased

  private void menuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditActionPerformed
    if (tbPokemon.getSelectedRow() != -1) {
      int baris = tbPokemon.getSelectedRow();
      String[] tipe = tbPokemon.getValueAt(baris, 2).toString().split(", ");
      String[] kemampuan = tbPokemon.getValueAt(baris, 6).toString().split(", ");

      tfID.setText(tbPokemon.getValueAt(baris, 0).toString());
      tfPokedexIDDlg.setText(tbPokemon.getValueAt(baris, 1).toString());
      tfNamaPokemonDlg.setText(tbPokemon.getValueAt(baris, 3).toString());
      tfTinggiDlg.setText(tbPokemon.getValueAt(baris, 4).toString());
      tfBeratDlg.setText(tbPokemon.getValueAt(baris, 5).toString());

      cbTipePokemon1Dlg.getModel().setSelectedItem(tipe[0]);
      if (tipe.length == 2) {
        cbTipePokemon2Dlg.getModel().setSelectedItem(tipe[1]);
      }

      cbKemampuanPokemon1Dlg.getModel().setSelectedItem(kemampuan[0]);
      if (kemampuan.length == 2) {
        cbKemampuanPokemon2Dlg.getModel().setSelectedItem(kemampuan[1]);
      }

      showDialog("Edit Pokémon", false);
    }
  }//GEN-LAST:event_menuEditActionPerformed

  private void menuHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHapusActionPerformed
    if (tbPokemon.getSelectedRow() != -1) {
      int baris = tbPokemon.getSelectedRow();
      String nama = tbPokemon.getValueAt(baris, 2).toString();

      int dialogResult = JOptionPane.showConfirmDialog(
              this,
              "Hapus Pokémon " + nama,
              "Hapus Pokemon",
              JOptionPane.YES_NO_OPTION);
      if (dialogResult == 0) {

      } else {
        System.out.println("No Option");
      }

    }
  }//GEN-LAST:event_menuHapusActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnClearDlg;
  private javax.swing.JButton btnTambah;
  private javax.swing.JButton btnTambahDlg;
  private javax.swing.JComboBox<ComboBoxItem> cbKemampuanPokemon1Dlg;
  private javax.swing.JComboBox<ComboBoxItem> cbKemampuanPokemon2Dlg;
  private javax.swing.JComboBox<ComboBoxItem> cbTipePokemon;
  private javax.swing.JComboBox<ComboBoxItem> cbTipePokemon1Dlg;
  private javax.swing.JComboBox<ComboBoxItem> cbTipePokemon2Dlg;
  private javax.swing.JLabel dialogTitle;
  private javax.swing.JDialog dlTambahPokemon;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JMenuItem menuEdit;
  private javax.swing.JMenuItem menuHapus;
  private javax.swing.JPopupMenu popUpTabel;
  private javax.swing.JTable tbPokemon;
  private javax.swing.JTextField tfBeratDlg;
  private javax.swing.JTextField tfCariNama;
  private javax.swing.JTextField tfID;
  private javax.swing.JTextField tfNamaPokemonDlg;
  private javax.swing.JTextField tfPokedexIDDlg;
  private javax.swing.JTextField tfTinggiDlg;
  // End of variables declaration//GEN-END:variables

  private void loadTable(String tipe) {
    DefaultTableModel model = new DefaultTableModel();

    crudPokemon.loadTabel(model, tipe);
    tbPokemon.setModel(model);
    tbPokemon.getColumnModel().getColumn(0).setMinWidth(0);
    tbPokemon.getColumnModel().getColumn(0).setMaxWidth(0);
    tbPokemon.getColumnModel().getColumn(0).setWidth(0);
  }

  private void addItem2ComboBox(JComboBox<ComboBoxItem> comboBox, String tabel, boolean isFromJFrame) {
    comboBox.removeAllItems();
    if (!isFromJFrame) {
      comboBox.addItem(new ComboBoxItem(0, "-- Pilih " + ((tabel.equals("tipe")) ? "tipe" : "kemampuan") + " --"));
    } else {
      comboBox.addItem(new ComboBoxItem(0, "Semua"));
    }

    try {
      ResultSet res = queryExe.querySelect("SELECT `id`,`nama` FROM `" + tabel + "` ORDER BY `nama` ASC");
      while (res.next()) {
        comboBox.addItem(new ComboBoxItem(res.getInt("id"), res.getString("nama")));
      }
    } catch (SQLException ex) {
      System.err.println("Error in getTipePokemon: " + ex.getMessage());
    } finally {
      queryExe.closeConn();
    }

  }

  private void getID() {
    try {
      ResultSet res = queryExe.querySelect("SELECT `id` FROM `pokemon` ORDER BY `id` DESC");
      if (res.next()) {
        tfID.setText(String.valueOf(res.getInt("id") + 1));
      } else {
        tfID.setText(String.valueOf(1));
      }
    } catch (SQLException ex) {
      System.err.println("Error in getID: " + ex.getMessage());
    } finally {
      queryExe.closeConn();
    }

  }

  private void clearFieldDialog() {
    tfID.setText("");
    tfPokedexIDDlg.setText("");
    tfNamaPokemonDlg.setText("");
    tfTinggiDlg.setText("");
    tfBeratDlg.setText("");
    cbTipePokemon1Dlg.setSelectedIndex(0);
    cbTipePokemon2Dlg.setSelectedIndex(0);
    cbKemampuanPokemon1Dlg.setSelectedIndex(0);
    cbKemampuanPokemon2Dlg.setSelectedIndex(0);
  }

  private void showDialog(String title, boolean isClear) {
    if (dlTambahPokemon.isActive()) {
      dlTambahPokemon.dispose();
    } else {
      dialogTitle.setText(title);
      if (isClear) {
        clearFieldDialog();
      }
      dlTambahPokemon.setLocationRelativeTo(this);
      dlTambahPokemon.setVisible(true);
    }
  }

}
