package view;

import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;

/**
 *
 * @author ZAFL
 */
public class FramePokedex extends javax.swing.JFrame {

  /**
   * Creates new form FramePokemon
   */
  public FramePokedex() {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    menuBar = new javax.swing.JMenuBar();
    menuMain = new javax.swing.JMenu();
    miLogin = new javax.swing.JMenuItem();
    miLogout = new javax.swing.JMenuItem();
    miExit = new javax.swing.JMenuItem();
    menuFrame = new javax.swing.JMenu();
    miPokemon = new javax.swing.JMenuItem();
    miKategori = new javax.swing.JMenuItem();
    miTipe = new javax.swing.JMenuItem();
    miKemampuan = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Pokedex");
    setMinimumSize(new java.awt.Dimension(950, 540));

    javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
    desktopPane.setLayout(desktopPaneLayout);
    desktopPaneLayout.setHorizontalGroup(
      desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 950, Short.MAX_VALUE)
    );
    desktopPaneLayout.setVerticalGroup(
      desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 517, Short.MAX_VALUE)
    );

    menuMain.setText("Menu");

    miLogin.setText("Login");
    miLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miLoginActionPerformed(evt);
      }
    });
    menuMain.add(miLogin);

    miLogout.setText("Logout");
    miLogout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miLogoutActionPerformed(evt);
      }
    });
    menuMain.add(miLogout);

    miExit.setText("Exit");
    miExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miExitActionPerformed(evt);
      }
    });
    menuMain.add(miExit);

    menuBar.add(menuMain);

    menuFrame.setText("Pokedex");

    miPokemon.setText("Pokemon");
    miPokemon.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miPokemonActionPerformed(evt);
      }
    });
    menuFrame.add(miPokemon);

    miKategori.setText("Kategori");
    miKategori.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miKategoriActionPerformed(evt);
      }
    });
    menuFrame.add(miKategori);

    miTipe.setText("Tipe");
    miTipe.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miTipeActionPerformed(evt);
      }
    });
    menuFrame.add(miTipe);

    miKemampuan.setText("Kemampuan");
    miKemampuan.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miKemampuanActionPerformed(evt);
      }
    });
    menuFrame.add(miKemampuan);

    menuBar.add(menuFrame);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void miLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoginActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_miLoginActionPerformed

  private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_miLogoutActionPerformed

  private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_miExitActionPerformed

  private void miPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPokemonActionPerformed
    FramePokemon frPokemon = new FramePokemon();
    addFrame(frPokemon);
  }//GEN-LAST:event_miPokemonActionPerformed

  private void miKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKategoriActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_miKategoriActionPerformed

  private void miTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTipeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_miTipeActionPerformed

  private void miKemampuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKemampuanActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_miKemampuanActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FramePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FramePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FramePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FramePokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FramePokedex().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuFrame;
  private javax.swing.JMenu menuMain;
  private javax.swing.JMenuItem miExit;
  private javax.swing.JMenuItem miKategori;
  private javax.swing.JMenuItem miKemampuan;
  private javax.swing.JMenuItem miLogin;
  private javax.swing.JMenuItem miLogout;
  private javax.swing.JMenuItem miPokemon;
  private javax.swing.JMenuItem miTipe;
  // End of variables declaration//GEN-END:variables

  private void addFrame(JInternalFrame internalFrame) {
    if (desktopPane.getAllFrames().length > 0) {
      desktopPane.remove(0);
    }
    desktopPane.add(internalFrame);
    try {
      internalFrame.setMaximum(true);
    } catch (PropertyVetoException pve) {
      System.err.println(pve.getMessage());
    }
    internalFrame.setVisible(true);
    internalFrame.toFront();
  }
}
